package com.lightsperfections.slackrelay.beans.logos.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.lightsperfections.slackrelay.beans.logos.HistoryEntry;

import java.time.LocalDateTime;

/**
 * Created with IntelliJ IDEA.
 * User: jhughes
 * Date: 12/30/15
 * Time: 9:43 AM
 */
@DynamoDBTable(tableName="HistoryEntry")
public class DynamoDBHistoryEntry implements HistoryEntry {

    // Id is just used for storing in Dynamo. It is not a usable piece of data, and is auto-generated.
    private String id;
    private String userName;
    private LocalDateTime entryTime;
    private String reference;

    public DynamoDBHistoryEntry (String userName, LocalDateTime entryTime, String reference) {
        this.userName = userName;
        this.entryTime = entryTime;
        this.reference = reference;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @Override
    @DynamoDBAttribute
    public String getUserName() {
        return userName;
    }

    @Override
    @DynamoDBAttribute
    public LocalDateTime getEntryTime() {
        return entryTime;
    }

    @Override
    @DynamoDBAttribute
    public String getReference() {
        return reference;
    }

}